# Deployment da aplicação conversao-temperatura
apiVersion: apps/v1					
kind: Deployment
metadata:
  name: meudeployment
spec:				
  selector:
    matchLabels: 
      app: web
  template:
    metadata:
      labels: 
        app: web
    spec:							
        containers:
          - name: web
            image: kubedevio/web-page:green 	
            ports: 
              - containerPort: 80

---

# Service da aplicação conversao-temperatura
apiVersion: v1				
kind: Service
metadata:
  name: web
spec:							
  selector: 					
    app: web
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30000
  type: NodePort 	